### PR TITLE
Fix code review changes #18

### LINKED ISSUE #18: Fix the code review changes

### PR DESCRIPTION
**Pull request by ferbin17**
Fixes #18

### CODE REVIEW

File: app/javascript/src/components/Dashboard/Notes/Note/index.jsx [hunk 1]
```diff
@@ -1,9 +1,9 @@
 import React from "react";
 
-import NoteContainer from "./Note/NoteContainer";
-import NoteContent from "./Note/NoteContent";
-import NoteFooter from "./Note/NoteFooter";
-import NoteHeader from "./Note/NoteHeader";
+import NoteContainer from "./NoteContainer";
+import NoteContent from "./NoteContent";
+import NoteFooter from "./NoteFooter";
+import NoteHeader from "./NoteHeader";
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Note/index.jsx]: Just name the components as `Container`, `Content` and avoid the `Note` prefix since these components are already within the `Note` namespace.

In any case where there is conflict, then import the component with the namespace, example:
```js
import NoteContainer from "./Note/Container";
```

**Review by yedhink — CHANGES_REQUESTED** [review]
@ferbin17 Added just one comment. Rest looks fine.

File: app/javascript/src/components/Dashboard/Notes/Note/index.jsx (hunk 1 above)
Comment (ferbin17) [reply app/javascript/src/components/Dashboard/Notes/Note/index.jsx]: @yedhink 
I have made the mentioned changes. Please have a look at the last commit.

File: app/javascript/src/components/Dashboard/Contacts/constants.js [hunk 2]
```diff
@@ -1,9 +1,10 @@
 import React from "react";
 
+import dayjs from "dayjs";
 import * as yup from "yup";
 
-import ContactAvatar from "./Contact/ContactAvatar";
-import ContactDetailText from "./Contact/ContactDetailText";
+import Avatar from "./Contact/Avatar";
+import DetailText from "./Contact/DetailText";
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Contacts/constants.js]: Given that there are multiple modules being imported from same namespace, add an `index.js` file within `Contact` and export all necessary modules.

**Review by yedhink — CHANGES_REQUESTED** [review]
@ferbin17 One minor comment. Once fixed, please go ahead and merge this PR and point out in the Slack channel that you've completed the review changes.

File: app/javascript/src/components/Dashboard/Contacts/constants.js (hunk 2 above)
Comment (ferbin17) [reply app/javascript/src/components/Dashboard/Contacts/constants.js]: I have made the changes and have merged the PR.

File: app/javascript/src/components/Dashboard/Contacts/constants.js [hunk 3]
```diff
@@ -3,8 +3,8 @@ import React from "react";
 import dayjs from "dayjs";
 import * as yup from "yup";
 
-import Avatar from "./Contact/Avatar";
-import DetailText from "./Contact/DetailText";
+import { Avatar } from "./Contact";
+import { DetailText } from "./Contact";
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Contacts/constants.js:7]: The whole point of adding an index.js was to import in a single line:
```suggestion
import { Avatar, DetailText } from "./Contact";
```

**Review by yedhink — COMMENTED** [review]
@ferbin17 No to make a PR or anything. Just to let you know the following:
